### ISSUE TITLE
Rename artifact to semanticdb-sbt

### ISSUE THREAD

**Issue by olafurpg** [scalameta/semanticdb-sbt#13]
Even if we wait with moving the package, we can rename the module. This will help scalafix documentation remain stable after the refactoring.

**Comment by dwijnand** [comment]
Looks like this is done: http://repo1.maven.org/maven2/org/scalameta/semanticdb-sbt_2.10.6/.

**Comment by gabro** [comment]
Yep: https://github.com/scalameta/semanticdb-sbt/commit/a3f165012c5e5be8c65a63d0f0f3e86df8fdc0e5
