### ISSUE TITLE
Cross-build to sbt 1

### ISSUE THREAD

**Issue by dwijnand** [scalameta/semanticdb-sbt#18]
I'd like to use this plugin in an sbt 1 build. Does that even make sense for semanticdb-sbt?

**Comment by gabro** [comment]
Not an expert in this area, but probably not, since sbt 1 runs on Scala 2.12 which is directly supported by Scalameta

**Comment by gabro** [comment]
Meaning: it should be possible to produce `.semanticdb` files for `.sbt` sources using the compiler plugin `semanticdb-scalac`, instead of this one. Not sure about the details though.

**Comment by olafurpg** [comment]
Correct @gabro this project becomes obsolete with sbt 1.0. That said, there are some features in this compiler plugin that are worth porting to semanticdb-scalac, most notably how multiple `Document.toByteArray` per *.sbt file are appended to `.semanticdb` files in https://github.com/scalameta/semanticdb-sbt/blob/189ae4e6e6031c80d1ed0f1f0eb91a59efab1083/sbthost/nsc/src/main/scala/scala/meta/internal/sbthost/SbthostPipeline.scala#L127-L131

**Comment by dwijnand** [comment]
sbt 1 support will be brought to semanticdb-scalac, so this issue is superseded by https://github.com/scalameta/scalameta/issues/1157.
